import '../models/pdf_form_template.dart';
import '../utils/pdf_form_templates.dart';

/// Service that provides pre-bundled PDF form templates
class BundledTemplatesService {
  /// Get all bundled templates
  static List<PdfFormTemplate> getBundledTemplates() {
    return [
      PdfFormTemplates.iqModificationCertificate,
      _fireAlarmServiceReport(),
      _emergencyLightingTest(),
      _generalMaintenanceForm(),
    ];
  }

  /// Fire Alarm Service Report template
  static PdfFormTemplate _fireAlarmServiceReport() {
    return PdfFormTemplate(
      id: 'bundled_fire_alarm_service',
      name: 'Fire Alarm Service Report',
      description: 'Standard fire alarm system service and inspection report',
      category: 'Fire Alarm',
      pdfPath: 'assets/templates/fire_alarm_service.pdf',
      isBundled: true,
      pageCount: 2,
      createdAt: DateTime(2024, 1, 1),
      fields: [
        // Page 1 - Header Info
        FormFieldDefinition(
          id: 'site_name',
          label: 'Site Name',
          type: FormFieldDefinitionType.text,
          x: 5,
          y: 5,
          width: 45,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'site_address',
          label: 'Site Address',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 12,
          width: 45,
          height: 10,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'visit_date',
          label: 'Visit Date',
          type: FormFieldDefinitionType.datePicker,
          x: 55,
          y: 5,
          width: 40,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'panel_type',
          label: 'Panel Type',
          type: FormFieldDefinitionType.dropdown,
          x: 55,
          y: 12,
          width: 40,
          height: 5,
          page: 0,
          options: ['Conventional', 'Addressable', 'Wireless', 'Hybrid', 'Other'],
        ),
        FormFieldDefinition(
          id: 'panel_location',
          label: 'Panel Location',
          type: FormFieldDefinitionType.text,
          x: 5,
          y: 25,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'num_zones',
          label: 'Number of Zones',
          type: FormFieldDefinitionType.text,
          x: 55,
          y: 25,
          width: 40,
          height: 5,
          page: 0,
        ),
        // Service checks
        FormFieldDefinition(
          id: 'panel_tested',
          label: 'Panel tested and functioning',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 35,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'batteries_checked',
          label: 'Batteries checked',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 42,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'sounders_tested',
          label: 'Sounders tested',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 49,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'call_points_tested',
          label: 'Call points tested',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 56,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'detectors_tested',
          label: 'Detectors tested',
          type: FormFieldDefinitionType.checkbox,
          x: 55,
          y: 35,
          width: 40,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'log_book_updated',
          label: 'Log book updated',
          type: FormFieldDefinitionType.checkbox,
          x: 55,
          y: 42,
          width: 40,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'system_status',
          label: 'Overall System Status',
          type: FormFieldDefinitionType.radioGroup,
          x: 5,
          y: 65,
          width: 90,
          height: 15,
          page: 0,
          options: ['Pass - No faults', 'Pass - Minor issues noted', 'Fail - Requires attention'],
        ),
        FormFieldDefinition(
          id: 'notes',
          label: 'Notes / Observations',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 82,
          width: 90,
          height: 15,
          page: 0,
        ),
        // Page 2 - Signatures
        FormFieldDefinition(
          id: 'defects_found',
          label: 'Defects Found',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 5,
          width: 90,
          height: 20,
          page: 1,
        ),
        FormFieldDefinition(
          id: 'recommendations',
          label: 'Recommendations',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 28,
          width: 90,
          height: 15,
          page: 1,
        ),
        FormFieldDefinition(
          id: 'engineer_signature',
          label: 'Engineer Signature',
          type: FormFieldDefinitionType.signature,
          x: 5,
          y: 50,
          width: 40,
          height: 15,
          page: 1,
          required: true,
        ),
        FormFieldDefinition(
          id: 'customer_signature',
          label: 'Customer Signature',
          type: FormFieldDefinitionType.signature,
          x: 55,
          y: 50,
          width: 40,
          height: 15,
          page: 1,
          required: true,
        ),
        FormFieldDefinition(
          id: 'customer_name',
          label: 'Customer Name (Print)',
          type: FormFieldDefinitionType.text,
          x: 55,
          y: 68,
          width: 40,
          height: 5,
          page: 1,
        ),
        FormFieldDefinition(
          id: 'photo_evidence',
          label: 'Photo Evidence',
          type: FormFieldDefinitionType.image,
          x: 5,
          y: 75,
          width: 40,
          height: 20,
          page: 1,
        ),
      ],
    );
  }

  /// Emergency Lighting Test template
  static PdfFormTemplate _emergencyLightingTest() {
    return PdfFormTemplate(
      id: 'bundled_emergency_lighting',
      name: 'Emergency Lighting Test',
      description: 'Monthly/Annual emergency lighting test certificate',
      category: 'Emergency Lighting',
      pdfPath: 'assets/templates/emergency_lighting.pdf',
      isBundled: true,
      pageCount: 1,
      createdAt: DateTime(2024, 1, 1),
      fields: [
        FormFieldDefinition(
          id: 'site_name',
          label: 'Site Name',
          type: FormFieldDefinitionType.text,
          x: 5,
          y: 5,
          width: 45,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'site_address',
          label: 'Site Address',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 12,
          width: 45,
          height: 10,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'test_date',
          label: 'Test Date',
          type: FormFieldDefinitionType.datePicker,
          x: 55,
          y: 5,
          width: 40,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'test_type',
          label: 'Test Type',
          type: FormFieldDefinitionType.radioGroup,
          x: 55,
          y: 12,
          width: 40,
          height: 12,
          page: 0,
          options: ['Monthly Function Test', 'Annual Duration Test'],
        ),
        FormFieldDefinition(
          id: 'num_luminaires',
          label: 'Number of Luminaires Tested',
          type: FormFieldDefinitionType.text,
          x: 5,
          y: 28,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'test_duration',
          label: 'Test Duration (minutes)',
          type: FormFieldDefinitionType.text,
          x: 55,
          y: 28,
          width: 40,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'all_lights_functioning',
          label: 'All lights functioning correctly',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 38,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'exit_signs_visible',
          label: 'Exit signs clearly visible',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 45,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'charging_indicators',
          label: 'All charging indicators on',
          type: FormFieldDefinitionType.checkbox,
          x: 55,
          y: 38,
          width: 40,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'defects_notes',
          label: 'Defects / Notes',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 55,
          width: 90,
          height: 15,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'engineer_signature',
          label: 'Engineer Signature',
          type: FormFieldDefinitionType.signature,
          x: 5,
          y: 75,
          width: 40,
          height: 12,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'customer_signature',
          label: 'Customer Signature',
          type: FormFieldDefinitionType.signature,
          x: 55,
          y: 75,
          width: 40,
          height: 12,
          page: 0,
        ),
      ],
    );
  }

  /// General Maintenance Form template
  static PdfFormTemplate _generalMaintenanceForm() {
    return PdfFormTemplate(
      id: 'bundled_general_maintenance',
      name: 'General Maintenance Form',
      description: 'General purpose maintenance and service form',
      category: 'Maintenance',
      pdfPath: 'assets/templates/general_maintenance.pdf',
      isBundled: true,
      pageCount: 1,
      createdAt: DateTime(2024, 1, 1),
      fields: [
        FormFieldDefinition(
          id: 'customer_name',
          label: 'Customer Name',
          type: FormFieldDefinitionType.text,
          x: 5,
          y: 5,
          width: 45,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'site_address',
          label: 'Site Address',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 12,
          width: 45,
          height: 10,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'visit_date',
          label: 'Visit Date',
          type: FormFieldDefinitionType.datePicker,
          x: 55,
          y: 5,
          width: 40,
          height: 5,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'job_type',
          label: 'Job Type',
          type: FormFieldDefinitionType.dropdown,
          x: 55,
          y: 12,
          width: 40,
          height: 5,
          page: 0,
          options: ['Scheduled Maintenance', 'Emergency Call-out', 'Installation', 'Repair', 'Inspection'],
        ),
        FormFieldDefinition(
          id: 'work_description',
          label: 'Description of Work',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 28,
          width: 90,
          height: 20,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'parts_used',
          label: 'Parts / Materials Used',
          type: FormFieldDefinitionType.multilineText,
          x: 5,
          y: 52,
          width: 90,
          height: 12,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'work_completed',
          label: 'Work completed satisfactorily',
          type: FormFieldDefinitionType.checkbox,
          x: 5,
          y: 68,
          width: 45,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'follow_up_required',
          label: 'Follow-up visit required',
          type: FormFieldDefinitionType.checkbox,
          x: 55,
          y: 68,
          width: 40,
          height: 5,
          page: 0,
        ),
        FormFieldDefinition(
          id: 'engineer_signature',
          label: 'Engineer Signature',
          type: FormFieldDefinitionType.signature,
          x: 5,
          y: 78,
          width: 40,
          height: 12,
          page: 0,
          required: true,
        ),
        FormFieldDefinition(
          id: 'customer_signature',
          label: 'Customer Signature',
          type: FormFieldDefinitionType.signature,
          x: 55,
          y: 78,
          width: 40,
          height: 12,
          page: 0,
          required: true,
        ),
      ],
    );
  }
}
