// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9C9NhIr7iDPV_1UoTNSzQGEkhy9g2PwE',
    appId: '1:218966840739:android:376a4c3850b9e4ee7b3616',
    messagingSenderId: '218966840739',
    projectId: 'firethings-51e00',
    storageBucket: 'firethings-51e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa1QpMut-vNUYIFjwkiLuM0e3_zH0zq3o',
    appId: '1:218966840739:ios:91ecd476aaaa477b7b3616',
    messagingSenderId: '218966840739',
    projectId: 'firethings-51e00',
    storageBucket: 'firethings-51e00.firebasestorage.app',
    iosBundleId: 'com.firethings.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqKJvJGHHNFcvgOma0fjR1gpMsF9ASQU',
    appId: '1:218966840739:web:19e4d14f2b47d20c7b3616',
    messagingSenderId: '218966840739',
    projectId: 'firethings-51e00',
    authDomain: 'firethings-51e00.firebaseapp.com',
    storageBucket: 'firethings-51e00.firebasestorage.app',
    measurementId: 'G-8N2ESV7GG1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa1QpMut-vNUYIFjwkiLuM0e3_zH0zq3o',
    appId: '1:218966840739:ios:836771bd03af42e17b3616',
    messagingSenderId: '218966840739',
    projectId: 'firethings-51e00',
    storageBucket: 'firethings-51e00.firebasestorage.app',
    iosBundleId: 'com.firethings.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLqKJvJGHHNFcvgOma0fjR1gpMsF9ASQU',
    appId: '1:218966840739:web:d5226d9d7fa380a77b3616',
    messagingSenderId: '218966840739',
    projectId: 'firethings-51e00',
    authDomain: 'firethings-51e00.firebaseapp.com',
    storageBucket: 'firethings-51e00.firebasestorage.app',
    measurementId: 'G-CTFZN73ZE8',
  );

}